using System.Globalization;
using System.Text;

namespace OccTypeComparison;

/// <summary>
/// Emits Consequences/Occupancy/OccupancyTypeDefaults.cs from the HEC-FIA canonical data —
/// the accepted source for the shared 40 default occupancy types (see results/DECISION.md).
/// </summary>
public static class DefaultsGenerator
{
    public static string Generate(List<CanonicalOccType> fiaTypes)
    {
        var code = new StringBuilder();
        code.Append("""
// <auto-generated>
// Generated by Tools/OccTypeComparison (--emit-defaults). Do not edit by hand — edit the
// source data and regenerate:
//   dotnet run --project Tools/OccTypeComparison -- --emit-defaults Consequences/Occupancy/OccupancyTypeDefaults.cs
//
// Source: HEC-FIA "Occupancy Type Defaults.sqlite" — the accepted source for the 40
// occupancy types shared with go-consequences occtypes.json (@ dff647c), including the
// HEC-FIA version of the AGR1 structure curve. See Tools/OccTypeComparison/results/DECISION.md.
//
// Damage function y-values are fractions (FIA percent / 100), matching Building.Compute,
// which multiplies value directly by GetYFromX(depth).
//
// Sixteen RES1 curves carry Normal per-ordinate standard deviations in the source; central
// values are transcribed here. The uncertainty data lives in
// Tools/OccTypeComparison/results/occtypes-fia.canonical.json for when UncertainOccupancyType matures.
// </auto-generated>

using Numerics.Data;

namespace Consequences.Occupancy;

public static class OccupancyTypeDefaults
{
    /// <summary>
    /// The 40 default occupancy types implemented by both HEC-FIA and go-consequences.
    /// Builds fresh instances on every call; OrderedPairedData is mutable, so callers get
    /// their own copies rather than shared static state.
    /// </summary>
    public static OccupancyType[] GetDefaults() =>
    [

""");

        foreach (CanonicalOccType occType in fiaTypes.OrderBy(t => t.Name, StringComparer.Ordinal))
        {
            CanonicalCurve structure = occType.Curves.Single(c => c.Component == "structure");
            CanonicalCurve contents = occType.Curves.Single(c => c.Component == "contents");
            string warned = occType.Parameters["All_Warned"];
            string mobilized = occType.Parameters["All_Mobilized"];

            code.Append($$"""
        // {{occType.Description}} ({{occType.DamageCategory}})
        new OccupancyType
        {
            Name = "{{occType.Name}}",
            StructureDamageFunction = {{Curve(structure)}},
            ContentDamageFunction = {{Curve(contents)}},
            CollectivelyWarned = {{warned}},
            CollectivelyMobilize = {{mobilized}},
        },

""");
        }

        code.Append("""
    ];
}

""");
        return code.ToString();
    }

    private static string Curve(CanonicalCurve curve)
    {
        string xs = string.Join(", ", curve.Xs.Select(x => x.ToString("0.##", CultureInfo.InvariantCulture)));
        string ys = string.Join(", ", curve.Ys.Select(y => (y / 100.0).ToString("0.########", CultureInfo.InvariantCulture)));
        return $$"""
new OrderedPairedData(
                new double[] { {{xs}} },
                new double[] { {{ys}} },
                strictOnX: true, SortOrder.Ascending, strictOnY: false, SortOrder.Ascending)
""";
    }
}
