using System.Globalization;
using System.Text;
using System.Web;

namespace OccTypeComparison;

public record ReportProvenance(string SqlitePath, string JsonUrl, string JsonCommit, string GeneratedOn);

/// <summary>
/// Renders the comparison as a single self-contained HTML page: no external scripts,
/// styles, or fonts, so it can be emailed or opened offline on the USACE network.
/// </summary>
public static class HtmlReport
{
    // Chart geometry
    private const int Width = 460;
    private const int Height = 260;
    private const int MarginLeft = 44, MarginRight = 12, MarginTop = 12, MarginBottom = 34;

    public static string Render(
        List<OccTypeComparisonResult> results,
        List<InventoryRow> inventory,
        ReportProvenance provenance)
    {
        var shared = results.Where(r => r.Fia is not null && r.Go is not null).ToList();
        var fiaOnly = results.Where(r => r.Go is null).ToList();
        var goOnly = results.Where(r => r.Fia is null).ToList();

        var allCurveComparisons = shared.SelectMany(r => r.CurveComparisons).ToList();
        int identical = allCurveComparisons.Count(c => c.Verdict == CurveVerdict.Identical);
        int minor = allCurveComparisons.Count(c => c.Verdict == CurveVerdict.Minor);
        int divergent = allCurveComparisons.Count(c => c.Verdict == CurveVerdict.Divergent);
        int missing = allCurveComparisons.Count(c => c.Verdict is CurveVerdict.MissingInFia or CurveVerdict.MissingInGo);

        var html = new StringBuilder();
        html.Append($$"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Occupancy Type Defaults — HEC-FIA vs go-consequences</title>
<style>
{{Css()}}
</style>
</head>
<body>
<div class="viz-root">
<header>
  <h1>Occupancy Type Defaults — source comparison</h1>
  <p class="subtitle">HEC-FIA SQLite defaults vs <code>go-consequences</code> occtypes.json, prepared for the ConsequencesCore defaults decision.</p>
  <p class="provenance">
    SQLite: <code>{{E(provenance.SqlitePath)}}</code> &nbsp;·&nbsp;
    JSON: <a href="{{E(provenance.JsonUrl)}}">USACE/go-consequences structures/occtypes.json</a> @ <code>{{E(provenance.JsonCommit)}}</code> &nbsp;·&nbsp;
    Generated {{E(provenance.GeneratedOn)}}
  </p>
</header>
""");

        AppendSummary(html, shared.Count, fiaOnly.Count, goOnly.Count, identical, minor, divergent, missing);
        AppendCoverage(html, results);
        AppendInventory(html, inventory, shared.Count + fiaOnly.Count, shared.Count + goOnly.Count);
        AppendMethodology(html);
        AppendSharedTypes(html, shared);
        AppendGoOnlyAppendix(html, goOnly);

        html.Append($$"""
<footer>Generated by Tools/OccTypeComparison in ConsequencesCore. Central values only are charted; see methodology for band definitions.</footer>
<div id="tooltip" role="status" aria-hidden="true"></div>
</div>
<script>
{{TooltipScript()}}
</script>
</body>
</html>
""");
        return html.ToString();
    }

    // ---------------------------------------------------------------- sections

    private static void AppendSummary(StringBuilder html, int shared, int fiaOnly, int goOnly,
        int identical, int minor, int divergent, int missing)
    {
        html.Append($"""
<section>
<h2>Summary</h2>
<div class="tiles">
  <div class="tile"><div class="tile-label">Shared occupancy types</div><div class="tile-value">{shared}</div></div>
  <div class="tile"><div class="tile-label">Only in HEC-FIA SQLite</div><div class="tile-value">{fiaOnly}</div></div>
  <div class="tile"><div class="tile-label">Only in go-consequences</div><div class="tile-value">{goOnly}</div></div>
</div>
<div class="tiles">
  <div class="tile"><div class="tile-label">Depth curves compared</div><div class="tile-value">{identical + minor + divergent + missing}</div></div>
  <div class="tile"><div class="tile-label"><span class="badge b-good">✓ Identical</span> max diff &lt; 0.5 pts</div><div class="tile-value">{identical}</div></div>
  <div class="tile"><div class="tile-label"><span class="badge b-warn">△ Minor</span> max diff &lt; 5 pts</div><div class="tile-value">{minor}</div></div>
  <div class="tile"><div class="tile-label"><span class="badge b-crit">✕ Divergent</span> max diff ≥ 5 pts</div><div class="tile-value">{divergent}</div></div>
</div>
</section>
""");
    }

    private static void AppendCoverage(StringBuilder html, List<OccTypeComparisonResult> results)
    {
        html.Append("""
<section>
<h2>Coverage matrix</h2>
<p>Which occupancy types each source defines. All HEC-FIA names also exist in go-consequences; the reverse does not hold.</p>
<div class="scroll"><table class="coverage">
<thead><tr><th>Occupancy type</th><th>HEC-FIA SQLite</th><th>go-consequences</th><th>Worst depth-curve verdict</th></tr></thead>
<tbody>
""");
        foreach (OccTypeComparisonResult result in results)
        {
            string verdictCell = "<span class=\"muted\">n/a — single source</span>";
            if (result.Fia is not null && result.Go is not null && result.CurveComparisons.Count > 0)
            {
                CurveComparison worst = result.CurveComparisons.OrderByDescending(c => c.MaxAbsDiff).First();
                verdictCell = $"{Badge(worst.Verdict)} <span class=\"muted\">max {worst.MaxAbsDiff.ToString("0.0", CultureInfo.InvariantCulture)} pts</span>";
            }
            html.Append($"""
<tr><td><a href="#{Anchor(result.Name)}">{E(result.Name)}</a></td>
<td class="center">{(result.Fia is not null ? "✓" : "—")}</td>
<td class="center">{(result.Go is not null ? "✓" : "—")}</td>
<td>{verdictCell}</td></tr>
""");
        }
        html.Append("</tbody></table></div></section>\n");
    }

    private static void AppendInventory(StringBuilder html, List<InventoryRow> inventory, int fiaTotal, int goTotal)
    {
        html.Append($"""
<section>
<h2>Attribute inventory — what each source carries</h2>
<p>Counts are occupancy types carrying the item (of {fiaTotal} HEC-FIA / {goTotal} go-consequences types). Items with a zero column exist in only one source — these are the gaps the experts must decide on.</p>
<div class="scroll"><table>
<thead><tr><th>Kind</th><th>Item</th><th>HEC-FIA SQLite</th><th>go-consequences</th></tr></thead>
<tbody>
""");
        foreach (InventoryRow row in inventory)
        {
            string cls = row.FiaCount == 0 || row.GoCount == 0 ? " class=\"exclusive\"" : "";
            html.Append($"<tr{cls}><td>{E(row.Kind)}</td><td><code>{E(row.Item)}</code></td>" +
                        $"<td class=\"center\">{(row.FiaCount == 0 ? "—" : row.FiaCount.ToString())}</td>" +
                        $"<td class=\"center\">{(row.GoCount == 0 ? "—" : row.GoCount.ToString())}</td></tr>\n");
        }
        html.Append("</tbody></table></div></section>\n");
    }

    private static void AppendMethodology(StringBuilder html)
    {
        html.Append("""
<section>
<h2>Methodology</h2>
<ul>
  <li><strong>Comparable ground:</strong> structure and contents <em>depth</em>-driven damage functions. go-consequences uses its <code>depth</code> driver (falling back to <code>default</code>, which mirrors it). Vehicle/other curves, erosion, salinity and wave drivers have no counterpart in the other source and are cataloged in the inventory instead.</li>
  <li><strong>Central values:</strong> charts and diffs use each ordinate's central estimate — Deterministic value, Triangular most-likely, Normal mean, Empirical histogram mean. HEC-FIA curve ordinates are deterministic except 16 curves carrying Normal standard deviations.</li>
  <li><strong>Uncertainty bands:</strong> shaded where a source has one — Triangular min→max, Normal ±2σ, Empirical min→max.</li>
  <li><strong>Diff metric:</strong> both curves evaluated on the union of their depth grids; outside a curve's range its endpoint value extends flat. Max/mean absolute difference is in percent-damage points.</li>
  <li><strong>Verdicts:</strong> Identical &lt; 0.5 pts · Minor &lt; 5 pts · Divergent ≥ 5 pts (max abs diff).</li>
</ul>
</section>
""");
    }

    private static void AppendSharedTypes(StringBuilder html, List<OccTypeComparisonResult> shared)
    {
        html.Append("""
<section>
<h2>Shared occupancy types — depth-damage curves</h2>
<p>Sorted most-divergent first, so the discussion agenda starts at the top. Hover any curve for values; raw ordinates are in the collapsed tables.</p>
""");
        foreach (OccTypeComparisonResult result in shared.OrderByDescending(r => r.Severity).ThenBy(r => r.Name, StringComparer.Ordinal))
        {
            html.Append($"""
<article class="occtype" id="{Anchor(result.Name)}">
<h3>{E(result.Name)} <span class="desc">{E(result.Fia?.Description ?? "")}</span>
    <span class="chip">{E(result.Fia?.DamageCategory ?? "")}</span></h3>
<div class="charts">
""");
            foreach (CurveComparison comparison in result.CurveComparisons)
            {
                AppendComparisonFigure(html, result.Name, comparison);
            }
            html.Append("</div>\n");
            AppendParameterDetails(html, result);
            html.Append("</article>\n");
        }
        html.Append("</section>\n");
    }

    private static void AppendComparisonFigure(StringBuilder html, string typeName, CurveComparison comparison)
    {
        string stats = comparison.Verdict is CurveVerdict.MissingInFia or CurveVerdict.MissingInGo
            ? ""
            : $" <span class=\"muted\">max {comparison.MaxAbsDiff.ToString("0.0", CultureInfo.InvariantCulture)} · mean {comparison.MeanAbsDiff.ToString("0.0", CultureInfo.InvariantCulture)} pts</span>";

        html.Append($"""
<figure>
<figcaption>
  <span class="fig-title">{E(Cap(comparison.Component))}</span>
  {Badge(comparison.Verdict)}{stats}
</figcaption>
<div class="legend">
  <span class="key"><span class="swatch s1"></span>HEC-FIA SQLite</span>
  <span class="key"><span class="swatch s2"></span>go-consequences</span>
</div>
{Chart(comparison.Fia, comparison.Go, $"{typeName} {comparison.Component}")}
{OrdinateTable(comparison)}
</figure>
""");
    }

    private static void AppendParameterDetails(StringBuilder html, OccTypeComparisonResult result)
    {
        if (result.Fia is null || result.Go is null) return;

        html.Append($"<details><summary>Parameters &amp; source-exclusive content for {E(result.Name)}</summary><div class=\"detail-grid\">");

        html.Append("<div><h4>HEC-FIA parameters (no go-consequences counterpart)</h4><table><tbody>");
        foreach ((string key, string value) in result.Fia.Parameters.OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            html.Append($"<tr><td><code>{E(key)}</code></td><td>{E(value)}</td></tr>");
        }
        html.Append("</tbody></table></div>");

        html.Append("<div><h4>go-consequences damage functions beyond depth</h4><table><tbody>");
        var extraCurves = result.Go.Curves
            .Where(c => c.Driver is not "depth" and not "default")
            .OrderBy(c => c.Component, StringComparer.Ordinal).ThenBy(c => c.Driver, StringComparer.Ordinal);
        bool any = false;
        foreach (CanonicalCurve curve in extraCurves)
        {
            any = true;
            html.Append($"<tr><td><code>{E(curve.Component)} × {E(curve.Driver)}</code></td><td>{E(curve.CurveSource ?? "")} <span class=\"muted\">({curve.Xs.Length} pts, uncertainty: {E(curve.UncertaintyKind)})</span></td></tr>");
        }
        if (!any) html.Append("<tr><td colspan=\"2\" class=\"muted\">none</td></tr>");

        var fiaExtra = result.Fia.Curves.Where(c => c.Component is "other" or "vehicle").ToList();
        if (fiaExtra.Count > 0)
        {
            html.Append("<tr><td colspan=\"2\"><h4>HEC-FIA damage functions beyond structure/contents</h4></td></tr>");
            foreach (CanonicalCurve curve in fiaExtra)
            {
                html.Append($"<tr><td><code>{E(curve.Component)} × depth</code></td><td><span class=\"muted\">{curve.Xs.Length} pts, uncertainty: {E(curve.UncertaintyKind)}</span></td></tr>");
            }
        }
        html.Append("</tbody></table></div></div></details>\n");
    }

    private static void AppendGoOnlyAppendix(StringBuilder html, List<OccTypeComparisonResult> goOnly)
    {
        if (goOnly.Count == 0) return;
        html.Append("""
<section>
<h2>Appendix — types only in go-consequences</h2>
<p>No HEC-FIA counterpart exists; shown for completeness of the decision space.</p>
""");
        foreach (OccTypeComparisonResult result in goOnly)
        {
            html.Append($"<article class=\"occtype\" id=\"{Anchor(result.Name)}\"><h3>{E(result.Name)}</h3><div class=\"charts\">");
            foreach (string component in new[] { "structure", "contents" })
            {
                CanonicalCurve? curve = Comparator.DepthCurve(result.Go!, component);
                if (curve is not null)
                {
                    html.Append($"""
<figure>
<figcaption><span class="fig-title">{E(Cap(component))}</span> <span class="muted">{E(curve.CurveSource ?? "")}</span></figcaption>
{Chart(null, curve, $"{result.Name} {component}")}
</figure>
""");
                }
                else
                {
                    // Most go-only types are NACCS coastal entries with no depth curve at all;
                    // list what they do carry so the decision space stays visible.
                    var drivers = result.Go!.Curves.Where(c => c.Component == component)
                        .Select(c => $"<li><code>{E(c.Driver)}</code> <span class=\"muted\">{E(c.CurveSource ?? "")}</span></li>");
                    html.Append($"""
<figure>
<figcaption><span class="fig-title">{E(Cap(component))}</span> <span class="muted">no depth-driven curve</span></figcaption>
<ul class="driver-list">{string.Concat(drivers)}</ul>
</figure>
""");
                }
            }
            html.Append("</div></article>\n");
        }
        html.Append("</section>\n");
    }

    // ---------------------------------------------------------------- chart (inline SVG)

    private static string Chart(CanonicalCurve? fia, CanonicalCurve? go, string chartId)
    {
        var curves = new List<(CanonicalCurve Curve, string SeriesClass, string SeriesName)>();
        if (fia is not null) curves.Add((fia, "s1", "HEC-FIA SQLite"));
        if (go is not null) curves.Add((go, "s2", "go-consequences"));
        if (curves.Count == 0) return "<div class=\"nodata\">No depth-driven curve.</div>";

        double xMin = curves.Min(c => c.Curve.Xs.Min());
        double xMax = curves.Max(c => c.Curve.Xs.Max());
        double yMax = Math.Max(100, curves.Max(c => (c.Curve.YMaxs ?? c.Curve.Ys).Max()));
        double yMin = 0;

        double PlotX(double x) => MarginLeft + (x - xMin) / (xMax - xMin) * (Width - MarginLeft - MarginRight);
        double PlotY(double y) => Height - MarginBottom - (y - yMin) / (yMax - yMin) * (Height - MarginTop - MarginBottom);

        var svg = new StringBuilder();
        svg.Append($"<svg viewBox=\"0 0 {Width} {Height}\" class=\"chart\" role=\"img\" aria-label=\"Depth-damage curves for {E(chartId)}\">");

        // Horizontal gridlines + y ticks
        foreach (double tick in Ticks(yMin, yMax, 4))
        {
            double y = PlotY(tick);
            svg.Append($"<line class=\"grid\" x1=\"{F(MarginLeft)}\" x2=\"{F(Width - MarginRight)}\" y1=\"{F(y)}\" y2=\"{F(y)}\"/>");
            svg.Append($"<text class=\"tick\" x=\"{F(MarginLeft - 6)}\" y=\"{F(y + 3)}\" text-anchor=\"end\">{F(tick)}</text>");
        }
        // X ticks + baseline
        foreach (double tick in Ticks(xMin, xMax, 6))
        {
            double x = PlotX(tick);
            svg.Append($"<text class=\"tick\" x=\"{F(x)}\" y=\"{F(Height - MarginBottom + 14)}\" text-anchor=\"middle\">{F(tick)}</text>");
        }
        svg.Append($"<line class=\"axis\" x1=\"{F(MarginLeft)}\" x2=\"{F(Width - MarginRight)}\" y1=\"{F(PlotY(0))}\" y2=\"{F(PlotY(0))}\"/>");

        // Axis titles (muted ink, never series-colored)
        svg.Append($"<text class=\"axis-title\" x=\"{F((MarginLeft + Width - MarginRight) / 2.0)}\" y=\"{F(Height - 4)}\" text-anchor=\"middle\">Depth above first floor (ft)</text>");
        svg.Append($"<text class=\"axis-title\" transform=\"translate(10,{F((MarginTop + Height - MarginBottom) / 2.0)}) rotate(-90)\" text-anchor=\"middle\">Damage (%)</text>");

        // Uncertainty bands first (washes under the lines)
        foreach ((CanonicalCurve curve, string seriesClass, _) in curves)
        {
            if (curve.YMins is null || curve.YMaxs is null) continue;
            var band = new StringBuilder("<path class=\"band ");
            band.Append(seriesClass).Append("\" d=\"M");
            for (int i = 0; i < curve.Xs.Length; i++)
                band.Append($"{F(PlotX(curve.Xs[i]))},{F(PlotY(Math.Min(curve.YMaxs[i], yMax)))} ");
            for (int i = curve.Xs.Length - 1; i >= 0; i--)
                band.Append($"{F(PlotX(curve.Xs[i]))},{F(PlotY(Math.Max(curve.YMins[i], yMin)))} ");
            band.Append("Z\"/>");
            svg.Append(band);
        }

        // Lines
        foreach ((CanonicalCurve curve, string seriesClass, _) in curves)
        {
            svg.Append($"<polyline class=\"line {seriesClass}\" points=\"");
            for (int i = 0; i < curve.Xs.Length; i++)
                svg.Append($"{F(PlotX(curve.Xs[i]))},{F(PlotY(curve.Ys[i]))} ");
            svg.Append("\"/>");
        }

        // Invisible hover targets, drawn last so they sit on top
        foreach ((CanonicalCurve curve, _, string seriesName) in curves)
        {
            for (int i = 0; i < curve.Xs.Length; i++)
            {
                string tip = $"{seriesName} · depth {F(curve.Xs[i])} ft → {F(Math.Round(curve.Ys[i], 1))}%";
                if (curve.YMins is not null && curve.YMaxs![i] > curve.YMins[i])
                    tip += $" [{F(Math.Round(curve.YMins[i], 1))}–{F(Math.Round(curve.YMaxs[i], 1))}]";
                svg.Append($"<circle class=\"hit\" cx=\"{F(PlotX(curve.Xs[i]))}\" cy=\"{F(PlotY(curve.Ys[i]))}\" r=\"9\" data-tip=\"{E(tip)}\"/>");
            }
        }

        svg.Append("</svg>");
        return svg.ToString();
    }

    private static string OrdinateTable(CurveComparison comparison)
    {
        var html = new StringBuilder("<details><summary>Raw ordinates</summary><div class=\"detail-grid\">");
        foreach ((CanonicalCurve? curve, string label) in new[] { (comparison.Fia, "HEC-FIA SQLite"), (comparison.Go, "go-consequences") })
        {
            html.Append($"<div><h4>{E(label)}</h4>");
            if (curve is null) { html.Append("<p class=\"muted\">absent</p></div>"); continue; }
            html.Append($"<p class=\"muted\">source: {E(curve.CurveSource ?? "—")} · uncertainty: {E(curve.UncertaintyKind)}</p>");
            html.Append("<table class=\"nums\"><thead><tr><th>Depth (ft)</th><th>Damage (%)</th>");
            bool hasBand = curve.YMins is not null;
            if (hasBand) html.Append("<th>Band</th>");
            html.Append("</tr></thead><tbody>");
            for (int i = 0; i < curve.Xs.Length; i++)
            {
                html.Append($"<tr><td>{F(curve.Xs[i])}</td><td>{F(Math.Round(curve.Ys[i], 2))}</td>");
                if (hasBand) html.Append($"<td>{F(Math.Round(curve.YMins![i], 2))} – {F(Math.Round(curve.YMaxs![i], 2))}</td>");
                html.Append("</tr>");
            }
            html.Append("</tbody></table></div>");
        }
        html.Append("</div></details>");
        return html.ToString();
    }

    // ---------------------------------------------------------------- helpers

    private static IEnumerable<double> Ticks(double min, double max, int approximateCount)
    {
        double rawStep = (max - min) / approximateCount;
        double magnitude = Math.Pow(10, Math.Floor(Math.Log10(rawStep)));
        double step = new[] { 1, 2, 2.5, 5, 10 }.Select(m => m * magnitude).First(s => s >= rawStep);
        for (double tick = Math.Ceiling(min / step) * step; tick <= max + step / 1000; tick += step)
            yield return Math.Round(tick, 6);
    }

    private static string Badge(CurveVerdict verdict) => verdict switch
    {
        CurveVerdict.Identical => "<span class=\"badge b-good\">✓ Identical</span>",
        CurveVerdict.Minor => "<span class=\"badge b-warn\">△ Minor</span>",
        CurveVerdict.Divergent => "<span class=\"badge b-crit\">✕ Divergent</span>",
        CurveVerdict.MissingInFia => "<span class=\"badge b-miss\">absent in HEC-FIA</span>",
        _ => "<span class=\"badge b-miss\">absent in go-consequences</span>",
    };

    private static string Anchor(string name) => "ot-" + name.Replace(' ', '-');
    private static string Cap(string s) => char.ToUpperInvariant(s[0]) + s[1..];
    private static string E(string s) => HttpUtility.HtmlEncode(s);
    private static string F(double v) => (v == 0 ? 0d : v).ToString("0.##", CultureInfo.InvariantCulture);

    private static string Css() => """
:root {
  color-scheme: light dark;
  --page: #f9f9f7; --surface-1: #fcfcfb; --ink: #0b0b0b; --ink-2: #52514e; --muted: #898781;
  --grid: #e1e0d9; --axisline: #c3c2b7; --border: rgba(11,11,11,0.10);
  --series-1: #2a78d6; --series-2: #1baf7a;
  --good: #0ca30c; --warn: #fab219; --crit: #d03b3b;
}
@media (prefers-color-scheme: dark) {
  :root {
    --page: #0d0d0d; --surface-1: #1a1a19; --ink: #ffffff; --ink-2: #c3c2b7; --muted: #898781;
    --grid: #2c2c2a; --axisline: #383835; --border: rgba(255,255,255,0.10);
    --series-1: #3987e5; --series-2: #199e70;
  }
}
* { box-sizing: border-box; margin: 0; }
body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; background: var(--page); color: var(--ink); line-height: 1.45; }
.viz-root { max-width: 1100px; margin: 0 auto; padding: 24px 20px 60px; }
h1 { font-size: 24px; margin-bottom: 4px; }
h2 { font-size: 18px; margin: 32px 0 8px; }
h3 { font-size: 15px; margin-bottom: 8px; }
h4 { font-size: 12px; color: var(--ink-2); margin: 8px 0 4px; }
.subtitle { color: var(--ink-2); }
.provenance { color: var(--muted); font-size: 12px; margin-top: 6px; }
.provenance a { color: inherit; }
code { font-size: 0.92em; }
section > p { color: var(--ink-2); font-size: 13px; margin-bottom: 10px; max-width: 78ch; }
.tiles { display: flex; flex-wrap: wrap; gap: 10px; margin: 10px 0; }
.tile { background: var(--surface-1); border: 1px solid var(--border); border-radius: 8px; padding: 10px 14px; min-width: 150px; }
.tile-label { font-size: 12px; color: var(--ink-2); }
.tile-value { font-size: 26px; font-weight: 600; }
.scroll { overflow-x: auto; }
table { border-collapse: collapse; font-size: 13px; background: var(--surface-1); border: 1px solid var(--border); border-radius: 8px; }
th, td { padding: 5px 10px; text-align: left; border-bottom: 1px solid var(--grid); }
th { color: var(--ink-2); font-weight: 600; font-size: 12px; }
tbody tr:last-child td { border-bottom: none; }
td.center, th.center { text-align: center; }
tr.exclusive td { background: color-mix(in srgb, var(--warn) 7%, var(--surface-1)); }
table.nums td, table.nums th { font-variant-numeric: tabular-nums; text-align: right; }
.muted { color: var(--muted); font-size: 12px; }
.badge { display: inline-block; font-size: 11px; font-weight: 600; padding: 1px 8px; border-radius: 999px; border: 1px solid; }
.b-good { color: var(--good); border-color: var(--good); }
.b-warn { color: color-mix(in srgb, var(--warn) 70%, var(--ink)); border-color: var(--warn); }
.b-crit { color: var(--crit); border-color: var(--crit); }
.b-miss { color: var(--muted); border-color: var(--muted); }
.occtype { background: var(--surface-1); border: 1px solid var(--border); border-radius: 10px; padding: 14px 16px; margin: 14px 0; }
.desc { font-weight: 400; color: var(--ink-2); font-size: 13px; }
.chip { font-size: 11px; color: var(--ink-2); border: 1px solid var(--border); border-radius: 999px; padding: 1px 8px; margin-left: 6px; vertical-align: middle; }
.charts { display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 16px; }
figure { min-width: 0; }
figcaption { font-size: 13px; margin-bottom: 2px; }
.fig-title { font-weight: 600; margin-right: 6px; }
.legend { display: flex; gap: 14px; font-size: 12px; color: var(--ink-2); margin: 4px 0; }
.key { display: inline-flex; align-items: center; gap: 5px; }
.swatch { width: 14px; height: 3px; border-radius: 2px; display: inline-block; }
.swatch.s1 { background: var(--series-1); }
.swatch.s2 { background: var(--series-2); }
svg.chart { width: 100%; height: auto; display: block; background: var(--surface-1); }
svg .grid { stroke: var(--grid); stroke-width: 1; }
svg .axis { stroke: var(--axisline); stroke-width: 1; }
svg .tick, svg .axis-title { fill: var(--muted); font-size: 10px; }
svg .line { fill: none; stroke-width: 2; stroke-linejoin: round; stroke-linecap: round; }
svg .line.s1 { stroke: var(--series-1); }
svg .line.s2 { stroke: var(--series-2); }
svg .band { opacity: 0.10; }
svg .band.s1 { fill: var(--series-1); }
svg .band.s2 { fill: var(--series-2); }
svg .hit { fill: transparent; }
.nodata { color: var(--muted); font-size: 13px; padding: 30px 0; }
.driver-list { list-style: none; padding: 8px 0; font-size: 13px; }
.driver-list li { padding: 2px 0; }
details { margin-top: 8px; }
summary { cursor: pointer; font-size: 12px; color: var(--ink-2); }
.detail-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 14px; margin-top: 8px; }
footer { margin-top: 40px; color: var(--muted); font-size: 12px; }
#tooltip { position: fixed; pointer-events: none; display: none; background: var(--surface-1);
  color: inherit; border: 1px solid rgba(127,127,127,0.4); border-radius: 6px; padding: 4px 8px;
  font: 12px system-ui, sans-serif; box-shadow: 0 2px 8px rgba(0,0,0,0.18); z-index: 10; max-width: 320px; }
""";

    private static string TooltipScript() => """
const tip = document.getElementById('tooltip');
document.addEventListener('mouseover', e => {
  const t = e.target.closest('.hit');
  if (!t) { tip.style.display = 'none'; return; }
  tip.textContent = t.dataset.tip;
  tip.style.display = 'block';
});
document.addEventListener('mousemove', e => {
  if (tip.style.display !== 'block') return;
  const pad = 12;
  let x = e.clientX + pad, y = e.clientY + pad;
  const r = tip.getBoundingClientRect();
  if (x + r.width > window.innerWidth - 4) x = e.clientX - r.width - pad;
  if (y + r.height > window.innerHeight - 4) y = e.clientY - r.height - pad;
  tip.style.left = x + 'px'; tip.style.top = y + 'px';
});
""";
}
